language: java
install: true
jdk:
- oraclejdk11
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew buildDocs publish --info --stacktrace"
- ls -laR ./build | grep -v .git
deploy:
  provider: releases
  on:
    branch: master
    tags: true
  file_glob: true
  file:
  - build/curriculum-improve_de*
  - build/curriculum-improve_en*
  - build/images
  skip_cleanup: true
  overwrite: true
env:
  global:
    secure: MEO3HEXjiBxXH8U4l0Gyo1IXmntMWeizmqb3rVlBC0+ypCH6VWhsWXXHFW0QN/HEUD9OYhZ3Lo6MeEFtIeq6dbPQgKsKyw1V3/e3cdglna12UIetuczMU4p9PBclRjcA5lhNQCOp5TbK56BrY+5jnWmmvzb7/oNXWmjXkTUcsAZ5EcCeNYEMUxhaRTk811h0PpBPVvF+ZgcuUOWMJoEepoTHWpMXuZt43iPQADc6SZ+1CQOt3eQGzaNsQINSnfg6H0ro36VqWsZuwLUTIjFMZyEG5x9myzizgB/OwNwSbPAmKlm4MuUanQOXaXbexSb9vyjGpRShGkzlVSA316n3FLOUOa6gRa3BGZ9NN7le3KB8TgqbIM4mCo6tdzszFOgAdn6f65QDIVGQVF7ZSDNVcDLEFJ0HM2hyVGbdt6hwEsP90FeKWN5Gq2oWiXa0Oat7bWv9bVgnG6zVnr+PFT37F+VW6pQNV77Y6xxV8lnworn6wpeVOwnhnPX5T/2KfxOpR6yCwImMnHIomI87idkfghWzfKlLu9hjIFPX3OIDMhVefJ74J6iNhdrGzqkRHM37IDW0Z4/rTNtNzLV24awMSQZOHJVRyzfcIJkCZXTEQVNwUiB1ud/onJyhrcR3TSiibOigkSi5Rk4S8F67DEf59hLgCtA1KyMMZjGC7Vxn3GI=
